import { AgentWorkspace } from '../types';

export interface HermesPythonExport {
  source: string;
  filename: string;
}

/**
 * Exports the agent workspace as a single Python bootstrap file
 * that instantiates the Hermes AIAgent class.
 */
export function exportToHermesPython(workspace: AgentWorkspace): HermesPythonExport {
  const manifest = workspace.manifest;
  const name = manifest.name || 'agent';
  const description = manifest.description || '';
  const safeName = name.toLowerCase().replace(/[^a-z0-9]/g, '_');
  const filename = `${safeName}_agent.py`;

  // 1. Module docstring
  let source = `"""\n${name} — ${description}\nGenerated by GitAgent Workbench. Requires: hermes-agent (NousResearch)\nInstall: pip install git+https://github.com/NousResearch/hermes-agent.git\n"""\n\n`;

  // 2. Imports
  source += `import os\nfrom run_agent import AIAgent\n\n`;

  // 3. SOUL constant
  const soulContent = workspace.soul || '';
  // Escape triple-quotes in SOUL.md content (replace """ with \"\"\")
  const escapedSoul = soulContent.replace(/"""/g, '\\"\\"\\"');
  source += `SOUL = """\n${escapedSoul}\n"""\n\n`;

  // 4. create_agent() factory function
  source += `def create_agent(api_key: str | None = None) -> AIAgent:\n`;
  source += `    """\n    Factory function to instantiate the configured AIAgent.\n    """\n`;
  source += `    return AIAgent(\n`;
  
  // Model mapping (OpenRouter format)
  const preferredModel = manifest.model?.preferred || workspace.generationConfig?.modelId || 'gemini-2.0-flash-exp';
  const providerId = workspace.generationConfig?.providerId || 'google';
  
  let modelString = preferredModel;
  // If it's already in provider/model format, keep it
  if (!preferredModel.includes('/')) {
    const providerMap: Record<string, string> = {
      anthropic: 'anthropic',
      openai: 'openai',
      google: 'google',
      mistral: 'mistral',
      openrouter: '' // Already in OpenRouter format
    };
    const prefix = providerMap[providerId] || '';
    modelString = prefix ? `${prefix}/${preferredModel}` : preferredModel;
  }
  
  source += `        model="${modelString}",\n`;
  source += `        quiet_mode=True,\n`;

  // ENABLED_TOOLSETS DERIVATION
  let toolsets: string[] = ['web', 'file', 'skills', 'memory'];
  if (workspace.toolPermissions?.matrix) {
    const matrix = workspace.toolPermissions.matrix;
    const allTools = new Set<string>();
    const subAgentNames = Object.keys(workspace.subAgents || {});
    
    Object.values(matrix).forEach(row => {
      Object.entries(row).forEach(([tool, enabled]) => {
        if (enabled && !subAgentNames.includes(tool)) {
          allTools.add(tool);
        }
      });
    });
    if (allTools.size > 0) {
      toolsets = Array.from(allTools);
    }
  } else if (workspace.hermesConfig) {
    // Simple regex to extract toolsets from YAML-like hermesConfig
    const match = workspace.hermesConfig.match(/toolsets:\s*\n(\s*-\s*.*\n)+/);
    if (match) {
      const list = match[0].split('\n')
        .slice(1)
        .map(line => line.trim().replace(/^- /, '').trim())
        .filter(Boolean);
      if (list.length > 0) toolsets = list;
    }
  }
  source += `        enabled_toolsets=${JSON.stringify(toolsets)},\n`;
  
  source += `        ephemeral_system_prompt=SOUL,\n`;
  source += `        max_iterations=90,\n`;

  // SKIP_CONTEXT_FILES
  const skipContextFiles = workspace.deploymentTargets?.some(t => t === 'api' || t === 'background') || false;
  source += `        skip_context_files=${skipContextFiles ? 'True' : 'False'},\n`;

  // SKIP_MEMORY
  const skipMemory = workspace.memory === null;
  source += `        skip_memory=${skipMemory ? 'True' : 'False'},\n`;

  source += `        api_key=api_key or os.environ.get("OPENROUTER_API_KEY"),\n`;

  // PLATFORM
  const deploymentTargets = workspace.deploymentTargets || [];
  const validPlatforms = ['telegram', 'discord', 'slack'];
  const platform = deploymentTargets.find(t => validPlatforms.includes(t)) || null;
  source += `        platform=${platform ? `"${platform}"` : 'None'},\n`;
  
  source += `    )\n\n`;

  // 5. Optional stubs (FastAPI, Discord, Telegram)
  if (deploymentTargets.includes('api')) {
    source += `# FastAPI endpoint\nfrom fastapi import FastAPI\nfrom pydantic import BaseModel\n\n`;
    source += `app = FastAPI(title="${name}")\n\n`;
    source += `class ChatRequest(BaseModel):\n    message: str\n    api_key: str | None = None\n\n`;
    source += `@app.post("/chat")\nasync def chat(request: ChatRequest):\n`;
    source += `    agent = create_agent(api_key=request.api_key)\n`;
    source += `    response = agent.chat(request.message)\n`;
    source += `    return {"response": response}\n\n`;
  }

  if (deploymentTargets.includes('discord')) {
    source += `# Discord bot stub\nimport discord\nfrom discord.ext import commands\n\n`;
    source += `intents = discord.Intents.default()\nintents.message_content = True\nbot = commands.Bot(command_prefix="!", intents=intents)\n\n`;
    source += `@bot.event\nasync def on_ready():\n    print(f'Logged in as {bot.user}')\n\n`;
    source += `@bot.command()\nasync def ask(ctx, *, question):\n`;
    source += `    agent = create_agent()\n`;
    source += `    response = agent.chat(question)\n`;
    source += `    await ctx.send(response)\n\n`;
  }

  if (deploymentTargets.includes('telegram')) {
    source += `# Telegram handler stub\nfrom telegram import Update\nfrom telegram.ext import ApplicationBuilder, ContextTypes, CommandHandler\n\n`;
    source += `async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):\n`;
    source += `    await context.bot.send_message(chat_id=update.effective_chat.id, text=f"I am ${name}. How can I help?")\n\n`;
    source += `async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):\n`;
    source += `    agent = create_agent()\n`;
    source += `    response = agent.chat(update.message.text)\n`;
    source += `    await context.bot.send_message(chat_id=update.effective_chat.id, text=response)\n\n`;
  }

  // 6. if __name__ == "__main__": example usage
  source += `if __name__ == "__main__":\n`;
  if (deploymentTargets.includes('api')) {
    source += `    import uvicorn\n    uvicorn.run(app, host="0.0.0.0", port=8000)\n`;
  } else if (deploymentTargets.includes('discord')) {
    source += `    bot.run(os.environ.get("DISCORD_TOKEN"))\n`;
  } else if (deploymentTargets.includes('telegram')) {
    source += `    application = ApplicationBuilder().token(os.environ.get("TELEGRAM_TOKEN")).build()\n`;
    source += `    application.add_handler(CommandHandler('start', start))\n`;
    source += `    # Add more handlers as needed\n`;
    source += `    application.run_polling()\n`;
  } else {
    source += `    # Example usage\n    agent = create_agent()\n    print(f"Agent '{name}' ready. Type 'exit' to quit.")\n    while True:\n        user_input = input("You: ")\n        if user_input.lower() == 'exit':\n            break\n        response = agent.chat(user_input)\n        print(f"Agent: {response}")\n`;
  }

  return { source, filename };
}
