import { AgentFramework } from './types';

export interface ToolMatrixEntry {
  framework: AgentFramework;
  frameworkLabel: string;
  name: string;
  functionDesc: string;
  permissions: string;
  circumstances: string;
  intents: ToolIntentCategory[];
}

export type ToolIntentCategory =
  | 'file_read'
  | 'file_write'
  | 'terminal_exec'
  | 'web_access'
  | 'subagent_delegate'
  | 'task_management'
  | 'user_interaction'
  | 'multimodal_media'
  | 'schedule_cron'
  | 'memory_session'
  | 'process_control'
  | 'advanced_tools';

export const TOOL_MATRIX: ToolMatrixEntry[] = [
  // ─── CLAUDE CODE ─────────────────────────────────────────────────────────────
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'Read',
    functionDesc: 'Reads text, image, PDF, and notebook files from the local filesystem.',
    permissions: 'Read local filesystem',
    circumstances: 'When needing to inspect existing code or documentation.',
    intents: ['file_read', 'multimodal_media']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'Write',
    functionDesc: 'Creates new files or completely overwrites existing files with new content.',
    permissions: 'Write local filesystem',
    circumstances: 'When generating new code or replacing entire files.',
    intents: ['file_write']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'Edit',
    functionDesc: 'Performs exact string replacement edits on existing codebase files.',
    permissions: 'Write local filesystem',
    circumstances: 'When making targeted modifications to existing code.',
    intents: ['file_write']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'Glob',
    functionDesc: 'Finds files matching specified naming and directory patterns using glob syntax.',
    permissions: 'Read local filesystem',
    circumstances: 'When searching for files by name or pattern.',
    intents: ['file_read']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'Grep',
    functionDesc: 'Searches file contents for regular expression patterns powered by ripgrep.',
    permissions: 'Read local filesystem',
    circumstances: 'When searching for specific text within files.',
    intents: ['file_read']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'Bash',
    functionDesc: 'Executes shell commands in a persistent working directory session.',
    permissions: 'Execute shell commands',
    circumstances: 'When needing to run terminal commands or scripts.',
    intents: ['terminal_exec']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'Task',
    functionDesc: 'Spawns autonomous subagents to execute complex multi-step tasks.',
    permissions: 'Spawn subagents',
    circumstances: 'When delegating complex, multi-step tasks.',
    intents: ['subagent_delegate']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'WebFetch',
    functionDesc: 'Fetches and extracts text content from a specified URL.',
    permissions: 'Network access',
    circumstances: 'When retrieving content from a specific URL.',
    intents: ['web_access']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'WebSearch',
    functionDesc: 'Searches the web for up-to-date documentation and online information.',
    permissions: 'Network access',
    circumstances: 'When searching the web for information.',
    intents: ['web_access']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'TodoWrite',
    functionDesc: 'Manages task lists and tracks progress during coding sessions.',
    permissions: 'Manage tasks',
    circumstances: 'When tracking progress during coding sessions.',
    intents: ['task_management']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'AskUserQuestion',
    functionDesc: 'Asks interactive questions to gather requirements or clarify ambiguities.',
    permissions: 'Interact with user',
    circumstances: 'When requiring clarification or input from the user.',
    intents: ['user_interaction']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'NotebookEdit',
    functionDesc: 'Modifies and updates cells within Jupyter notebook files.',
    permissions: 'Write local filesystem',
    circumstances: 'When modifying Jupyter notebook cells.',
    intents: ['file_write']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'BashOutput',
    functionDesc: 'Retrieves output generated by active or background shell processes.',
    permissions: 'Read shell output',
    circumstances: 'When checking the results of background processes.',
    intents: ['terminal_exec', 'process_control']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'KillShell',
    functionDesc: 'Terminates active background shell commands and processes.',
    permissions: 'Manage processes',
    circumstances: 'When terminating active background commands.',
    intents: ['process_control']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'EnterPlanMode',
    functionDesc: 'Switches agent execution into planning mode before writing code.',
    permissions: 'Change execution mode',
    circumstances: 'When preparing a plan before writing code.',
    intents: ['task_management']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'ExitPlanMode',
    functionDesc: 'Presents proposed engineering plan for approval and exits plan mode.',
    permissions: 'Change execution mode',
    circumstances: 'When presenting a plan for approval.',
    intents: ['task_management', 'user_interaction']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'LSP',
    functionDesc: 'Queries language servers for definitions, references, and type diagnostics.',
    permissions: 'Query language server',
    circumstances: 'When needing code definitions or diagnostics.',
    intents: ['advanced_tools', 'file_read']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'CronCreate',
    functionDesc: 'Schedules recurring or delayed prompt tasks within active session.',
    permissions: 'Schedule tasks',
    circumstances: 'When setting up recurring or delayed tasks.',
    intents: ['schedule_cron']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'CronDelete',
    functionDesc: 'Cancels previously scheduled tasks using task identifiers.',
    permissions: 'Schedule tasks',
    circumstances: 'When canceling scheduled tasks.',
    intents: ['schedule_cron']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'CronList',
    functionDesc: 'Lists all scheduled active and pending session tasks.',
    permissions: 'Schedule tasks',
    circumstances: 'When reviewing scheduled tasks.',
    intents: ['schedule_cron']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'EnterWorktree',
    functionDesc: 'Creates and switches into isolated git worktree environment.',
    permissions: 'Manage git worktrees',
    circumstances: 'When isolating changes in a new environment.',
    intents: ['advanced_tools', 'file_write']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'ExitWorktree',
    functionDesc: 'Exits current git worktree and returns to original directory.',
    permissions: 'Manage git worktrees',
    circumstances: 'When returning to the original git environment.',
    intents: ['advanced_tools']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'Monitor',
    functionDesc: 'Runs commands in background while streaming output logs back.',
    permissions: 'Execute shell commands',
    circumstances: 'When running background commands and streaming logs.',
    intents: ['terminal_exec', 'process_control']
  },
  {
    framework: 'claude_code',
    frameworkLabel: 'Claude Code',
    name: 'PushNotification',
    functionDesc: 'Sends desktop notifications or mobile push alerts for completed tasks.',
    permissions: 'Send notifications',
    circumstances: 'When alerting the user about completed tasks.',
    intents: ['user_interaction']
  },

  // ─── HERMES AGENT ────────────────────────────────────────────────────────────
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'web_search',
    functionDesc: 'Searches web search engines for online information and links.',
    permissions: 'Network access',
    circumstances: 'When searching search engines for online information.',
    intents: ['web_access']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'web_extract',
    functionDesc: 'Scrapes and extracts full text content from target web pages.',
    permissions: 'Network access',
    circumstances: 'When scraping full text content from web pages.',
    intents: ['web_access']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'terminal',
    functionDesc: 'Executes shell commands across local or isolated container backends.',
    permissions: 'Execute shell commands',
    circumstances: 'When running shell commands across backends.',
    intents: ['terminal_exec']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'process',
    functionDesc: 'Polls status and terminates background shell execution processes.',
    permissions: 'Manage processes',
    circumstances: 'When polling or terminating background shell processes.',
    intents: ['process_control', 'terminal_exec']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'read_file',
    functionDesc: 'Reads text files with line numbering, pagination, and transcoding.',
    permissions: 'Read local filesystem',
    circumstances: 'When reading text files with pagination.',
    intents: ['file_read']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'write_file',
    functionDesc: 'Writes content to files, completely replacing existing contents.',
    permissions: 'Write local filesystem',
    circumstances: 'When writing or replacing file contents.',
    intents: ['file_write']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'patch',
    functionDesc: 'Performs targeted find-and-replace file modifications using fuzzy matching.',
    permissions: 'Write local filesystem',
    circumstances: 'When performing targeted find-and-replace modifications.',
    intents: ['file_write']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'search_files',
    functionDesc: 'Searches file contents via ripgrep or matches path glob patterns.',
    permissions: 'Read local filesystem',
    circumstances: 'When searching file contents or matching glob patterns.',
    intents: ['file_read']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'browser_navigate',
    functionDesc: 'Navigates headless browser to a specified web URL.',
    permissions: 'Network access',
    circumstances: 'When navigating a headless browser to a URL.',
    intents: ['web_access', 'multimodal_media']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'browser_snapshot',
    functionDesc: 'Captures text-based accessibility tree snapshot of active browser page.',
    permissions: 'Read browser state',
    circumstances: 'When capturing accessibility tree snapshots.',
    intents: ['web_access']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'browser_vision',
    functionDesc: 'Takes page visual screenshots for multimodal vision analysis.',
    permissions: 'Read browser state',
    circumstances: 'When taking visual screenshots of pages.',
    intents: ['multimodal_media', 'web_access']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'vision_analyze',
    functionDesc: 'Analyzes images, PDFs, and charts using multimodal vision models.',
    permissions: 'Analyze images',
    circumstances: 'When processing images, PDFs, or charts.',
    intents: ['multimodal_media', 'file_read']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'image_generate',
    functionDesc: 'Generates images from text descriptions via integrated API services.',
    permissions: 'Generate images',
    circumstances: 'When creating images from text descriptions.',
    intents: ['multimodal_media']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'text_to_speech',
    functionDesc: 'Converts written text into spoken audio files.',
    permissions: 'Generate audio',
    circumstances: 'When converting written text to spoken audio.',
    intents: ['multimodal_media']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'todo',
    functionDesc: 'Manages task items and tracks agent execution plans.',
    permissions: 'Manage tasks',
    circumstances: 'When tracking agent execution plans.',
    intents: ['task_management']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'clarify',
    functionDesc: 'Prompts user with questions to resolve task ambiguities.',
    permissions: 'Interact with user',
    circumstances: 'When resolving task ambiguities with the user.',
    intents: ['user_interaction']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'execute_code',
    functionDesc: 'Executes Python code scripts inside sandboxed environments.',
    permissions: 'Execute code',
    circumstances: 'When running Python scripts in a sandbox.',
    intents: ['terminal_exec', 'advanced_tools']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'delegate_task',
    functionDesc: 'Spawns isolated subagent instances for parallel task execution.',
    permissions: 'Spawn subagents',
    circumstances: 'When running tasks in parallel via subagents.',
    intents: ['subagent_delegate']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'memory',
    functionDesc: 'Stores, retrieves, and manages persistent cross-session knowledge.',
    permissions: 'Manage memory',
    circumstances: 'When storing or retrieving persistent knowledge.',
    intents: ['memory_session']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'session_search',
    functionDesc: 'Retrieves historical session transcripts and past context records.',
    permissions: 'Read session history',
    circumstances: 'When retrieving historical transcripts.',
    intents: ['memory_session']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'cronjob',
    functionDesc: 'Schedules and manages recurring automated background tasks.',
    permissions: 'Schedule tasks',
    circumstances: 'When managing automated background tasks.',
    intents: ['schedule_cron']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'x_search',
    functionDesc: 'Searches X posts and threads via xAI integration.',
    permissions: 'Network access',
    circumstances: 'When searching X posts and threads.',
    intents: ['web_access']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'computer_use',
    functionDesc: 'Executes background macOS desktop interactions via SkyLight SPI.',
    permissions: 'Control desktop',
    circumstances: 'When executing background macOS interactions.',
    intents: ['advanced_tools']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'tool_search',
    functionDesc: 'Searches catalog of deferred Model Context Protocol tools.',
    permissions: 'Search tools',
    circumstances: 'When looking up deferred Model Context Protocol tools.',
    intents: ['advanced_tools']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'tool_describe',
    functionDesc: 'Loads full parameter schema for a specific deferred tool.',
    permissions: 'Read tool schema',
    circumstances: 'When loading parameter schemas for deferred tools.',
    intents: ['advanced_tools']
  },
  {
    framework: 'hermes_agent',
    frameworkLabel: 'Hermes Agent',
    name: 'tool_call',
    functionDesc: 'Invokes a deferred tool using loaded schema arguments.',
    permissions: 'Execute tools',
    circumstances: 'When invoking deferred tools with arguments.',
    intents: ['advanced_tools']
  },

  // ─── GOOGLE ANTIGRAVITY ──────────────────────────────────────────────────────
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'list_directory',
    functionDesc: 'Lists contents and file structures within directories.',
    permissions: 'Read local filesystem',
    circumstances: 'When viewing contents of directories.',
    intents: ['file_read']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'search_directory',
    functionDesc: 'Searches file contents across workspace directories.',
    permissions: 'Read local filesystem',
    circumstances: 'When searching file contents across directories.',
    intents: ['file_read']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'find_file',
    functionDesc: 'Finds workspace files matching specific path patterns.',
    permissions: 'Read local filesystem',
    circumstances: 'When finding files matching specific patterns.',
    intents: ['file_read']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'view_file',
    functionDesc: 'Reads and displays contents of targeted workspace files.',
    permissions: 'Read local filesystem',
    circumstances: 'When reading contents of specific files.',
    intents: ['file_read']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'create_file',
    functionDesc: 'Creates new files with specified text content.',
    permissions: 'Write local filesystem',
    circumstances: 'When creating new files with text content.',
    intents: ['file_write']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'edit_file',
    functionDesc: 'Modifies existing files by applying code changes.',
    permissions: 'Write local filesystem',
    circumstances: 'When modifying existing files.',
    intents: ['file_write']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'run_command',
    functionDesc: 'Executes shell commands in system workspace environment.',
    permissions: 'Execute shell commands',
    circumstances: 'When running shell commands in the workspace.',
    intents: ['terminal_exec']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'ask_question',
    functionDesc: 'Prompts user interactively for required clarification or input.',
    permissions: 'Interact with user',
    circumstances: 'When prompting the user for clarification.',
    intents: ['user_interaction']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'start_subagent',
    functionDesc: 'Spawns child subagent for parallel task delegation.',
    permissions: 'Spawn subagents',
    circumstances: 'When delegating tasks to a child subagent.',
    intents: ['subagent_delegate']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'generate_image',
    functionDesc: 'Generates or edits visual images using Nanobanana models.',
    permissions: 'Generate images',
    circumstances: 'When creating or editing visual images.',
    intents: ['multimodal_media']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'search_web',
    functionDesc: 'Performs online web searches using Google Search.',
    permissions: 'Network access',
    circumstances: 'When performing online web searches.',
    intents: ['web_access']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'read_url_content',
    functionDesc: 'Fetches and extracts text content from web URLs.',
    permissions: 'Network access',
    circumstances: 'When fetching text content from URLs.',
    intents: ['web_access']
  },
  {
    framework: 'google_antigravity',
    frameworkLabel: 'Google Antigravity',
    name: 'finish',
    functionDesc: 'Concludes agent task execution and returns final output.',
    permissions: 'Conclude task',
    circumstances: 'When returning the final output of a task.',
    intents: ['task_management']
  },

  // ─── MISTRAL VIBE ────────────────────────────────────────────────────────────
  {
    framework: 'mistral_vibe',
    frameworkLabel: 'Mistral Vibe',
    name: 'read',
    functionDesc: 'Reads file contents from the project repository.',
    permissions: 'Read local filesystem',
    circumstances: 'When reading file contents from the repository.',
    intents: ['file_read']
  },
  {
    framework: 'mistral_vibe',
    frameworkLabel: 'Mistral Vibe',
    name: 'write_file',
    functionDesc: 'Creates new files without overwriting existing files.',
    permissions: 'Write local filesystem',
    circumstances: 'When creating new files without overwriting.',
    intents: ['file_write']
  },
  {
    framework: 'mistral_vibe',
    frameworkLabel: 'Mistral Vibe',
    name: 'edit',
    functionDesc: 'Applies targeted diff patches to existing codebase files.',
    permissions: 'Write local filesystem',
    circumstances: 'When applying diff patches to codebase files.',
    intents: ['file_write']
  },
  {
    framework: 'mistral_vibe',
    frameworkLabel: 'Mistral Vibe',
    name: 'grep',
    functionDesc: 'Recursively searches codebase files using regular expressions.',
    permissions: 'Read local filesystem',
    circumstances: 'When recursively searching codebase files.',
    intents: ['file_read']
  },
  {
    framework: 'mistral_vibe',
    frameworkLabel: 'Mistral Vibe',
    name: 'bash',
    functionDesc: 'Executes shell commands within managed terminal sessions.',
    permissions: 'Execute shell commands',
    circumstances: 'When running shell commands in terminal sessions.',
    intents: ['terminal_exec']
  },
  {
    framework: 'mistral_vibe',
    frameworkLabel: 'Mistral Vibe',
    name: 'todo',
    functionDesc: 'Manages internal task lists to track agent work.',
    permissions: 'Manage tasks',
    circumstances: 'When tracking internal agent work lists.',
    intents: ['task_management']
  },
  {
    framework: 'mistral_vibe',
    frameworkLabel: 'Mistral Vibe',
    name: 'ask_user_question',
    functionDesc: 'Asks interactive clarifying questions to gather user input.',
    permissions: 'Interact with user',
    circumstances: 'When gathering input through clarifying questions.',
    intents: ['user_interaction']
  },
  {
    framework: 'mistral_vibe',
    frameworkLabel: 'Mistral Vibe',
    name: 'explore',
    functionDesc: 'Read-only subagent for codebase exploration and skill loading.',
    permissions: 'Spawn subagents',
    circumstances: 'When exploring the codebase in a read-only manner.',
    intents: ['subagent_delegate', 'file_read']
  }
];

export const FRAMEWORK_TOOL_ENTRIES: Record<AgentFramework, ToolMatrixEntry[]> = {
  claude_code: TOOL_MATRIX.filter(t => t.framework === 'claude_code'),
  hermes_agent: TOOL_MATRIX.filter(t => t.framework === 'hermes_agent'),
  google_antigravity: TOOL_MATRIX.filter(t => t.framework === 'google_antigravity'),
  mistral_vibe: TOOL_MATRIX.filter(t => t.framework === 'mistral_vibe')
};

export const FRAMEWORK_CANONICAL_NAMES: Record<AgentFramework, string[]> = {
  claude_code: FRAMEWORK_TOOL_ENTRIES.claude_code.map(t => t.name),
  hermes_agent: FRAMEWORK_TOOL_ENTRIES.hermes_agent.map(t => t.name),
  google_antigravity: FRAMEWORK_TOOL_ENTRIES.google_antigravity.map(t => t.name),
  mistral_vibe: FRAMEWORK_TOOL_ENTRIES.mistral_vibe.map(t => t.name)
};
