import React, { useState, useEffect, useMemo, useRef } from 'react';
import { useAgentWorkspace } from '../../context/AgentContext';
import { useSettings } from '../../context/SettingsContext';
import { assembleSystemPrompt } from '../../../lib/gitagent/assembleSystemPrompt';
import yaml from 'js-yaml';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { 
  Copy, 
  Check, 
  Code, 
  MessageSquare, 
  Activity, 
  ShieldCheck, 
  Terminal, 
  Send, 
  RotateCcw, 
  Bot, 
  User, 
  Sparkles,
  Layers,
  FileCode,
  Download,
  CheckCircle2,
  AlertCircle,
  Cpu
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { AgentFlowDiagram } from './AgentFlowDiagram';

interface ChatMsg {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

export function AgentLivePreview({ onToggleCollapse }: { onToggleCollapse?: () => void }) {
  const { state } = useAgentWorkspace();
  const { settings } = useSettings();

  const [activeTab, setActiveTab] = useState<string>('code');
  const [codeType, setCodeType] = useState<'yaml' | 'prompt' | 'json' | 'python'>('yaml');
  const [copied, setCopied] = useState<string | null>(null);

  // Test Chat state
  const [chatMessages, setChatMessages] = useState<ChatMsg[]>([
    {
      id: 'init',
      role: 'assistant',
      content: `Hello! I'm ${state.manifest.name || 'your agent'}. You can test my behavior and responses here in real-time.`,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    }
  ]);
  const [chatInput, setChatInput] = useState('');
  const [isChatSending, setIsChatSending] = useState(false);
  const chatScrollRef = useRef<HTMLDivElement>(null);

  // Generated artifacts
  const systemPrompt = useMemo(() => assembleSystemPrompt(state), [state]);
  const manifestYaml = useMemo(() => {
    try {
      return yaml.dump(state.manifest, { indent: 2, skipInvalid: true });
    } catch {
      return '# YAML serialization error';
    }
  }, [state.manifest]);

  const settingsJson = useMemo(() => {
    return JSON.stringify({
      name: state.manifest.name || 'agent',
      model: state.manifest.model || { preferred: settings.modelId },
      tools: state.manifest.tools || [],
      runtime: state.manifest.runtime || {},
      parameters: settings.parameters || {}
    }, null, 2);
  }, [state.manifest, settings]);

  const pythonScript = useMemo(() => {
    const name = (state.manifest.name || 'agent').replace(/-/g, '_');
    return `"""
${state.manifest.name || 'Agent'} Runner Script
Generated by GitAgent Studio
"""

import os
from google import genai

client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

SYSTEM_PROMPT = """${systemPrompt.replace(/"""/g, "'''")}"""

def run_agent(user_input: str):
    response = client.models.generate_content(
        model="${settings.modelId || 'gemini-3.7-flash'}",
        contents=user_input,
        config={
            "system_instruction": SYSTEM_PROMPT,
            "temperature": ${settings.parameters?.temperature ?? 0.7},
        }
    )
    return response.text

if __name__ == "__main__":
    import sys
    query = sys.argv[1] if len(sys.argv) > 1 else "Hello!"
    print(run_agent(query))
`;
  }, [state, systemPrompt, settings]);

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  const handleSendTest = async () => {
    if (!chatInput.trim() || isChatSending) return;

    const userText = chatInput.trim();
    const userMsg: ChatMsg = {
      id: Date.now().toString(),
      role: 'user',
      content: userText,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setChatMessages(prev => [...prev, userMsg]);
    setChatInput('');
    setIsChatSending(true);

    try {
      const response = await fetch('/api/compute/v1', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          providerId: settings.providerId || 'google',
          modelId: settings.modelId || 'gemini-3.7-flash',
          options: settings.parameters,
          prompt: {
            system: systemPrompt,
            messages: [
              ...chatMessages.map(m => ({ role: m.role, content: m.content })),
              { role: 'user', content: userText }
            ]
          }
        })
      });

      if (!response.ok) {
        throw new Error('Test call failed');
      }

      const data = await response.json();
      const reply = data.text || data.object?.explanation || "Response received.";

      setChatMessages(prev => [
        ...prev,
        {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: reply,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }
      ]);
    } catch (e: any) {
      setChatMessages(prev => [
        ...prev,
        {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: `[Simulation Error]: ${e.message || 'Check model settings and API key.'}`,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }
      ]);
    } finally {
      setIsChatSending(false);
      setTimeout(() => {
        if (chatScrollRef.current) {
          chatScrollRef.current.scrollTop = chatScrollRef.current.scrollHeight;
        }
      }, 100);
    }
  };

  // Validation Score calculation
  const readinessCheck = useMemo(() => {
    const checks = [
      { label: "Agent Identity Defined", ok: !!state.manifest.name && !!state.manifest.description },
      { label: "System Soul Configured", ok: !!state.soul && state.soul.length > 20 },
      { label: "Execution Rules Configured", ok: !!state.rules && state.rules.length > 20 },
      { label: "Model Assigned", ok: !!settings.modelId },
      { label: "Tools / Capabilities Set", ok: (state.manifest.tools?.length || 0) > 0 || (state.manifest.skills?.length || 0) > 0 },
    ];
    const passed = checks.filter(c => c.ok).length;
    const score = Math.round((passed / checks.length) * 100);
    return { checks, score };
  }, [state, settings]);

  return (
    <div className="flex flex-col h-full bg-card/60 border-l border-border/50 select-none overflow-hidden">
      {/* Top Header */}
      <div className="px-4 py-3 border-b border-border/50 bg-background/50 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-2">
          <Activity className="h-4 w-4 text-primary" />
          <span className="text-xs font-bold uppercase tracking-wider text-foreground">
            Inspector & Verification
          </span>
        </div>

        <div className="flex items-center gap-2">
          <Badge 
            variant="outline" 
            className={cn(
              "text-[10px] font-mono px-2 py-0.5",
              readinessCheck.score >= 80 ? "bg-emerald-500/10 text-emerald-600 border-emerald-500/20" : "bg-amber-500/10 text-amber-600 border-amber-500/20"
            )}
          >
            {readinessCheck.score}% Ready
          </Badge>
        </div>
      </div>

      {/* Main Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col min-h-0">
        <div className="px-4 pt-2 border-b border-border/40 bg-muted/20 shrink-0">
          <TabsList className="grid grid-cols-4 h-9 w-full bg-background/60 p-0.5">
            <TabsTrigger value="code" className="text-[11px] font-semibold gap-1 px-1">
              <Code className="h-3.5 w-3.5" /> Manifest
            </TabsTrigger>
            <TabsTrigger value="chat" className="text-[11px] font-semibold gap-1 px-1">
              <MessageSquare className="h-3.5 w-3.5" /> Test Lab
            </TabsTrigger>
            <TabsTrigger value="flow" className="text-[11px] font-semibold gap-1 px-1">
              <Layers className="h-3.5 w-3.5" /> Flow
            </TabsTrigger>
            <TabsTrigger value="health" className="text-[11px] font-semibold gap-1 px-1">
              <ShieldCheck className="h-3.5 w-3.5" /> Readiness
            </TabsTrigger>
          </TabsList>
        </div>

        {/* Tab 1: Code & Manifest */}
        <TabsContent value="code" className="flex-1 flex flex-col m-0 p-0 min-h-0 focus-visible:outline-none">
          {/* Subtabs for Code Type */}
          <div className="px-4 py-2 border-b border-border/40 bg-muted/10 flex items-center justify-between shrink-0">
            <div className="flex gap-1">
              <Button
                variant={codeType === 'yaml' ? 'secondary' : 'ghost'}
                size="sm"
                className="h-6 text-[10px] px-2"
                onClick={() => setCodeType('yaml')}
              >
                manifest.yaml
              </Button>
              <Button
                variant={codeType === 'prompt' ? 'secondary' : 'ghost'}
                size="sm"
                className="h-6 text-[10px] px-2"
                onClick={() => setCodeType('prompt')}
              >
                PROMPT.md
              </Button>
              <Button
                variant={codeType === 'json' ? 'secondary' : 'ghost'}
                size="sm"
                className="h-6 text-[10px] px-2"
                onClick={() => setCodeType('json')}
              >
                settings.json
              </Button>
              <Button
                variant={codeType === 'python' ? 'secondary' : 'ghost'}
                size="sm"
                className="h-6 text-[10px] px-2"
                onClick={() => setCodeType('python')}
              >
                agent.py
              </Button>
            </div>

            <Button
              variant="ghost"
              size="sm"
              className="h-6 text-[10px] px-2 gap-1"
              onClick={() => {
                const text = codeType === 'yaml' ? manifestYaml : codeType === 'prompt' ? systemPrompt : codeType === 'json' ? settingsJson : pythonScript;
                handleCopy(text, codeType);
              }}
            >
              {copied === codeType ? <Check className="h-3 w-3 text-emerald-500" /> : <Copy className="h-3 w-3" />}
              {copied === codeType ? 'Copied' : 'Copy'}
            </Button>
          </div>

          <div className="flex-1 overflow-auto p-4 font-mono text-[11px] leading-relaxed whitespace-pre bg-[#0B0F19] text-[#E2E8F0] select-text">
            {codeType === 'yaml' && (manifestYaml || '# Empty manifest')}
            {codeType === 'prompt' && (systemPrompt || '# System prompt will be assembled here')}
            {codeType === 'json' && settingsJson}
            {codeType === 'python' && pythonScript}
          </div>
        </TabsContent>

        {/* Tab 2: Test Lab / Playground */}
        <TabsContent value="chat" className="flex-1 flex flex-col m-0 p-0 min-h-0 focus-visible:outline-none">
          <div className="px-4 py-2 border-b border-border/40 bg-muted/10 flex items-center justify-between text-xs text-muted-foreground shrink-0">
            <span className="font-mono text-[10px] flex items-center gap-1.5">
              <Cpu className="h-3 w-3 text-primary" />
              {settings.modelId || 'gemini-3.7-flash'}
            </span>
            <Button
              variant="ghost"
              size="sm"
              className="h-6 text-[10px] px-2 gap-1 text-muted-foreground hover:text-foreground"
              onClick={() => setChatMessages([])}
            >
              <RotateCcw className="h-3 w-3" /> Clear
            </Button>
          </div>

          <div ref={chatScrollRef} className="flex-1 overflow-y-auto p-4 space-y-3 bg-[#0B0F19]/40">
            {chatMessages.map(m => (
              <div
                key={m.id}
                className={cn(
                  "flex gap-2.5 max-w-[90%]",
                  m.role === 'user' ? "ml-auto flex-row-reverse" : "mr-auto"
                )}
              >
                <div
                  className={cn(
                    "w-6 h-6 rounded-full flex items-center justify-center text-[10px] shrink-0 font-bold",
                    m.role === 'user' ? "bg-primary text-white" : "bg-[#1E293B] text-[#A855F7] border border-[#334155]"
                  )}
                >
                  {m.role === 'user' ? <User className="h-3 w-3" /> : <Bot className="h-3 w-3" />}
                </div>

                <div
                  className={cn(
                    "p-3 rounded-xl text-xs leading-relaxed shadow-sm",
                    m.role === 'user'
                      ? "bg-primary text-primary-foreground rounded-tr-none"
                      : "bg-[#161F33] text-[#F1F5F9] border border-[#26334D] rounded-tl-none"
                  )}
                >
                  <p className="whitespace-pre-wrap">{m.content}</p>
                  <span className="block text-[9px] opacity-60 mt-1 font-mono text-right">
                    {m.timestamp}
                  </span>
                </div>
              </div>
            ))}
            {isChatSending && (
              <div className="flex gap-2 items-center text-xs text-muted-foreground italic pl-2">
                <span className="h-2 w-2 rounded-full bg-primary animate-ping" />
                {state.manifest.name || 'Agent'} is thinking...
              </div>
            )}
          </div>

          <div className="p-3 border-t border-border/50 bg-background/80 shrink-0">
            <div className="flex gap-2">
              <Input
                placeholder={`Ask ${state.manifest.name || 'agent'} anything...`}
                value={chatInput}
                onChange={e => setChatInput(e.target.value)}
                onKeyDown={e => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    handleSendTest();
                  }
                }}
                disabled={isChatSending}
                className="h-9 text-xs bg-card/60"
              />
              <Button
                size="sm"
                className="h-9 px-3"
                onClick={handleSendTest}
                disabled={!chatInput.trim() || isChatSending}
              >
                <Send className="h-3.5 w-3.5" />
              </Button>
            </div>
          </div>
        </TabsContent>

        {/* Tab 3: Workflow Flow Graph */}
        <TabsContent value="flow" className="flex-1 flex flex-col m-0 p-3 min-h-0 focus-visible:outline-none overflow-hidden">
          <AgentFlowDiagram />
        </TabsContent>

        {/* Tab 4: Readiness & Health */}
        <TabsContent value="health" className="flex-1 overflow-y-auto p-4 m-0 space-y-4 focus-visible:outline-none">
          <div className="p-4 bg-muted/20 border border-border/50 rounded-xl space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold">Deployment Readiness</span>
              <span className="text-xs font-bold text-primary">{readinessCheck.score}%</span>
            </div>
            <div className="w-full bg-muted rounded-full h-2 overflow-hidden">
              <div 
                className="bg-primary h-full transition-all duration-500" 
                style={{ width: `${readinessCheck.score}%` }} 
              />
            </div>
          </div>

          <div className="space-y-2">
            <h4 className="text-[11px] font-bold uppercase tracking-wider text-muted-foreground px-1">
              Configuration Checklist
            </h4>
            <div className="space-y-1.5">
              {readinessCheck.checks.map((chk, idx) => (
                <div 
                  key={idx} 
                  className={cn(
                    "flex items-center justify-between p-2.5 rounded-lg border text-xs transition-all",
                    chk.ok ? "bg-emerald-500/5 border-emerald-500/20 text-foreground" : "bg-amber-500/5 border-amber-500/20 text-muted-foreground"
                  )}
                >
                  <span className="flex items-center gap-2 font-medium">
                    {chk.ok ? (
                      <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0" />
                    ) : (
                      <AlertCircle className="h-4 w-4 text-amber-500 shrink-0" />
                    )}
                    {chk.label}
                  </span>
                  <Badge variant={chk.ok ? "default" : "outline"} className="text-[9px] h-5">
                    {chk.ok ? "Passed" : "Action Needed"}
                  </Badge>
                </div>
              ))}
            </div>
          </div>

          <div className="p-3 bg-blue-500/10 border border-blue-500/20 rounded-lg text-xs space-y-1">
            <span className="font-bold text-blue-600 dark:text-blue-400 block">Pro Tip</span>
            <p className="text-muted-foreground text-[11px]">
              Use the AI Architect prompt bar in the center panel to auto-generate or refine any missing soul rules or tool configurations in a single turn.
            </p>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
